name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract repository name
        shell: bash
        run: echo "##[set-output name=name;]$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        id: extract_repository_name

      - name: Build Static
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          check-latest: true
      - run: npm install
      - run: GHA_NAME=${{ steps.extract_repository_name.outputs.name }} npm run build

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
