name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Extract repository name
      #   shell: bash
      #   run: echo "##[set-output name=name;]$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
      #   id: extract_repository_name
      - name: Extract repository name
        run: echo ::set-env name=GHA_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - name: Extract branch name
        run: echo ::set-env name=GHA_BRANCH::$(echo $GITHUB_REF | awk -F / '{print $3}')
        shell: bash

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          check-latest: true
      - run: npm install
      - run: npm run build
      # - run: npm install -g @11ty/eleventy --unsafe-perm
      # - run: npm install
      # - run: eleventy --output _dist --pathprefix $GHA_NAME
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3.8.0
      #   with:
      #     PUBLISH_DIR: _dist
      #     PUBLISH_BRANCH: gh-pages
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
