name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Extract repository name
        shell: bash
        run: echo "##[set-output name=name;]$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        id: extract_repository_name
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --output _dist --pathprefix ${{ steps.extract_repository_name.outputs.name }}
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          PUBLISH_DIR: _dist
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
